-- CreateEnum
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'USER', 'HEAD_OF_TRADE', 'FINANCE_CONTROLLER', 'ACCOUNTS_OFFICER', 'REGIONAL_MANAGER', 'AREA_MANAGER', 'TERRITORY_OFFICER', 'BUSINESS_MANAGER', 'POINT_IN_CHARGE');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'BLOCKED', 'DELETED');

-- CreateTable
CREATE TABLE "user" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "role" "Role" NOT NULL DEFAULT 'USER',
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "needPasswordChange" BOOLEAN NOT NULL DEFAULT false,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "deletedAt" TIMESTAMP(3),
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "id" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "userId" TEXT NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account" (
    "id" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMP(3),
    "refreshTokenExpiresAt" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "verification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "retailers" (
    "id" TEXT NOT NULL,
    "prismID" TEXT NOT NULL,
    "partnerCode" TEXT,
    "region" TEXT NOT NULL,
    "area" TEXT NOT NULL,
    "territory" TEXT NOT NULL,
    "house" TEXT NOT NULL,
    "point" TEXT NOT NULL,
    "clusterName" TEXT NOT NULL,
    "clusterType" TEXT NOT NULL,
    "geoClass" TEXT NOT NULL,
    "routeNumber" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "retailerName" TEXT NOT NULL,
    "ownerName" TEXT NOT NULL,
    "contactNumber" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "subChannel" TEXT NOT NULL,
    "superTPG" TEXT NOT NULL,
    "tpg" TEXT NOT NULL,
    "pmmInformation" TEXT,
    "dccScope" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "retailers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sku_name" (
    "id" TEXT NOT NULL,
    "retailerId" TEXT NOT NULL,
    "bhSf20hl" INTEGER NOT NULL DEFAULT 0,
    "bhSf12hl" INTEGER NOT NULL DEFAULT 0,
    "bhFfBoxOuter" INTEGER NOT NULL DEFAULT 0,
    "bhSfBopp20s" INTEGER NOT NULL DEFAULT 0,
    "bhSfLep20hl" INTEGER NOT NULL DEFAULT 0,
    "bhSfLep12hl" INTEGER NOT NULL DEFAULT 0,
    "bhSfLep" INTEGER NOT NULL DEFAULT 0,
    "bhSfLep1" INTEGER NOT NULL DEFAULT 0,
    "bhSfLep2" INTEGER NOT NULL DEFAULT 0,
    "bhBg20hl" INTEGER NOT NULL DEFAULT 0,
    "bhBgLep20hl" INTEGER NOT NULL DEFAULT 0,
    "bhBg12hl" INTEGER NOT NULL DEFAULT 0,
    "bhBgBopp20s" INTEGER NOT NULL DEFAULT 0,
    "bhBgPug12hl" INTEGER NOT NULL DEFAULT 0,
    "bhBgLep12hl" INTEGER NOT NULL DEFAULT 0,
    "bhBgLep" INTEGER NOT NULL DEFAULT 0,
    "bhBgLep1" INTEGER NOT NULL DEFAULT 0,
    "bhBgLep2" INTEGER NOT NULL DEFAULT 0,
    "bhBgLep20hlOld" INTEGER NOT NULL DEFAULT 0,
    "bhSw20hl" INTEGER NOT NULL DEFAULT 0,
    "bhSwBopp20s" INTEGER NOT NULL DEFAULT 0,
    "bhSwLep20hl" INTEGER NOT NULL DEFAULT 0,
    "bhSwLep1" INTEGER NOT NULL DEFAULT 0,
    "bhSw12hl" INTEGER NOT NULL DEFAULT 0,
    "bhSwLep2" INTEGER NOT NULL DEFAULT 0,
    "bhPt20hl" INTEGER NOT NULL DEFAULT 0,
    "bhPtLep1" INTEGER NOT NULL DEFAULT 0,
    "bhPtLep2" INTEGER NOT NULL DEFAULT 0,
    "bhFc" INTEGER NOT NULL DEFAULT 0,
    "bhBreeze20hlLepp" INTEGER NOT NULL DEFAULT 0,
    "bhFusion20hlLepp" INTEGER NOT NULL DEFAULT 0,
    "alchemyMix1" INTEGER NOT NULL DEFAULT 0,
    "alchemy7mg" INTEGER NOT NULL DEFAULT 0,
    "jpgl20hl" INTEGER NOT NULL DEFAULT 0,
    "jpglFfWp20hl" INTEGER NOT NULL DEFAULT 0,
    "jpgl12hl" INTEGER NOT NULL DEFAULT 0,
    "jpglFfWp12hl" INTEGER NOT NULL DEFAULT 0,
    "jpglLep" INTEGER NOT NULL DEFAULT 0,
    "jpSp20hl" INTEGER NOT NULL DEFAULT 0,
    "jpSpecialP20hl" INTEGER NOT NULL DEFAULT 0,
    "jpSw20hl" INTEGER NOT NULL DEFAULT 0,
    "jpglHd20hl" INTEGER NOT NULL DEFAULT 0,
    "jpSwWp20hl" INTEGER NOT NULL DEFAULT 0,
    "jpglHe20hl" INTEGER NOT NULL DEFAULT 0,
    "pmb20hl" INTEGER NOT NULL DEFAULT 0,
    "cap20hl" INTEGER NOT NULL DEFAULT 0,
    "lsSs20hl" INTEGER NOT NULL DEFAULT 0,
    "lsCc20hl" INTEGER NOT NULL DEFAULT 0,
    "lsCc20hlPug" INTEGER NOT NULL DEFAULT 0,
    "lsCc10hl" INTEGER NOT NULL DEFAULT 0,
    "lsOg20hl" INTEGER NOT NULL DEFAULT 0,
    "lsOg20hlPug" INTEGER NOT NULL DEFAULT 0,
    "lsBc20hlLepp" INTEGER NOT NULL DEFAULT 0,
    "lsBc20hlPug" INTEGER NOT NULL DEFAULT 0,
    "lsBc10hl" INTEGER NOT NULL DEFAULT 0,
    "lsFt20hlLepp" INTEGER NOT NULL DEFAULT 0,
    "lsFt20hlPug" INTEGER NOT NULL DEFAULT 0,
    "lsFt10hl" INTEGER NOT NULL DEFAULT 0,
    "lsRed20hlLepp" INTEGER NOT NULL DEFAULT 0,
    "lsRed20hlPug" INTEGER NOT NULL DEFAULT 0,
    "luckiesMint20hl" INTEGER NOT NULL DEFAULT 0,
    "luckiesFf20hl" INTEGER NOT NULL DEFAULT 0,
    "luckiesCitrus20hl" INTEGER NOT NULL DEFAULT 0,
    "srf20hl" INTEGER NOT NULL DEFAULT 0,
    "srf10hl" INTEGER NOT NULL DEFAULT 0,
    "srf10ss" INTEGER NOT NULL DEFAULT 0,
    "starClickLep20h" INTEGER NOT NULL DEFAULT 0,
    "starClickLep10h" INTEGER NOT NULL DEFAULT 0,
    "srl20h" INTEGER NOT NULL DEFAULT 0,
    "starFfWp10hl" INTEGER NOT NULL DEFAULT 0,
    "srl10h" INTEGER NOT NULL DEFAULT 0,
    "srFrs20hl" INTEGER NOT NULL DEFAULT 0,
    "srFrs10hl" INTEGER NOT NULL DEFAULT 0,
    "srneo20hl" INTEGER NOT NULL DEFAULT 0,
    "srneo10hl" INTEGER NOT NULL DEFAULT 0,
    "srn20hl" INTEGER NOT NULL DEFAULT 0,
    "srn10hl" INTEGER NOT NULL DEFAULT 0,
    "srf20hlMarket" INTEGER NOT NULL DEFAULT 0,
    "srf10hlMarket" INTEGER NOT NULL DEFAULT 0,
    "srn20hlMarket" INTEGER NOT NULL DEFAULT 0,
    "srn10hlMarket" INTEGER NOT NULL DEFAULT 0,
    "wls20hl" INTEGER NOT NULL DEFAULT 0,
    "wls10hl" INTEGER NOT NULL DEFAULT 0,
    "starSw20hl" INTEGER NOT NULL DEFAULT 0,
    "starSwitch20hl" INTEGER NOT NULL DEFAULT 0,
    "plWp20hl" INTEGER NOT NULL DEFAULT 0,
    "pl20hl" INTEGER NOT NULL DEFAULT 0,
    "plLep20h" INTEGER NOT NULL DEFAULT 0,
    "pll20h" INTEGER NOT NULL DEFAULT 0,
    "pllp20hl" INTEGER NOT NULL DEFAULT 0,
    "pllp220hl" INTEGER NOT NULL DEFAULT 0,
    "derby20hl" INTEGER NOT NULL DEFAULT 0,
    "derbyWp20hl" INTEGER NOT NULL DEFAULT 0,
    "derby10hl" INTEGER NOT NULL DEFAULT 0,
    "derbyWp10hl" INTEGER NOT NULL DEFAULT 0,
    "derby20hlLep" INTEGER NOT NULL DEFAULT 0,
    "derby10hlLep" INTEGER NOT NULL DEFAULT 0,
    "db10ss" INTEGER NOT NULL DEFAULT 0,
    "dbLep20h" INTEGER NOT NULL DEFAULT 0,
    "dbLep10h" INTEGER NOT NULL DEFAULT 0,
    "db20hlOld" INTEGER NOT NULL DEFAULT 0,
    "db10hlOld" INTEGER NOT NULL DEFAULT 0,
    "dblp20hl" INTEGER NOT NULL DEFAULT 0,
    "dblp10hl" INTEGER NOT NULL DEFAULT 0,
    "dblp220hl" INTEGER NOT NULL DEFAULT 0,
    "dblp210hl" INTEGER NOT NULL DEFAULT 0,
    "derbyStyle20hl" INTEGER NOT NULL DEFAULT 0,
    "dbStyleWp20hl" INTEGER NOT NULL DEFAULT 0,
    "derbyStyle10hl" INTEGER NOT NULL DEFAULT 0,
    "dbStyleWp10hl" INTEGER NOT NULL DEFAULT 0,
    "derbySt20hlLep" INTEGER NOT NULL DEFAULT 0,
    "derbySt10hlLep" INTEGER NOT NULL DEFAULT 0,
    "dbst20hl" INTEGER NOT NULL DEFAULT 0,
    "dbst20hlOld" INTEGER NOT NULL DEFAULT 0,
    "dbSelect20hl" INTEGER NOT NULL DEFAULT 0,
    "dbSelect10hl" INTEGER NOT NULL DEFAULT 0,
    "dbst10hlOld" INTEGER NOT NULL DEFAULT 0,
    "dbst10hl" INTEGER NOT NULL DEFAULT 0,
    "dbDeluxe20hl" INTEGER NOT NULL DEFAULT 0,
    "dbDeluxe10hl" INTEGER NOT NULL DEFAULT 0,
    "dbsLep20h" INTEGER NOT NULL DEFAULT 0,
    "dbsLep10h" INTEGER NOT NULL DEFAULT 0,
    "dbs10s" INTEGER NOT NULL DEFAULT 0,
    "dbsp20hl" INTEGER NOT NULL DEFAULT 0,
    "dbsp10hl" INTEGER NOT NULL DEFAULT 0,
    "derbyPlus20hl" INTEGER NOT NULL DEFAULT 0,
    "derbyPlus10hl" INTEGER NOT NULL DEFAULT 0,
    "db20hl" INTEGER NOT NULL DEFAULT 0,
    "db10hl" INTEGER NOT NULL DEFAULT 0,
    "hw20hl" INTEGER NOT NULL DEFAULT 0,
    "hw10hl" INTEGER NOT NULL DEFAULT 0,
    "hwd20hl" INTEGER NOT NULL DEFAULT 0,
    "hwd10hl" INTEGER NOT NULL DEFAULT 0,
    "hwd10ss" INTEGER NOT NULL DEFAULT 0,
    "hwlp20hl" INTEGER NOT NULL DEFAULT 0,
    "hwg20hl" INTEGER NOT NULL DEFAULT 0,
    "flg20hl" INTEGER NOT NULL DEFAULT 0,
    "hlGlWp20hl" INTEGER NOT NULL DEFAULT 0,
    "hwGl20hl" INTEGER NOT NULL DEFAULT 0,
    "flg10hl" INTEGER NOT NULL DEFAULT 0,
    "rg20hl" INTEGER NOT NULL DEFAULT 0,
    "rg10hl" INTEGER NOT NULL DEFAULT 0,
    "rlGl20hl" INTEGER NOT NULL DEFAULT 0,
    "rlGl10hl" INTEGER NOT NULL DEFAULT 0,
    "rn20hl" INTEGER NOT NULL DEFAULT 0,
    "rn10hl" INTEGER NOT NULL DEFAULT 0,
    "rlNx20hl" INTEGER NOT NULL DEFAULT 0,
    "rlNx10hl" INTEGER NOT NULL DEFAULT 0,
    "rls20hl" INTEGER NOT NULL DEFAULT 0,
    "rls10hl" INTEGER NOT NULL DEFAULT 0,
    "rlLs10hl" INTEGER NOT NULL DEFAULT 0,
    "rm20hl" INTEGER NOT NULL DEFAULT 0,
    "rm10hl" INTEGER NOT NULL DEFAULT 0,
    "royalsLc20hl" INTEGER NOT NULL DEFAULT 0,
    "royalsLc10hl" INTEGER NOT NULL DEFAULT 0,
    "royalsRed10hl" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sku_name_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");

-- CreateIndex
CREATE UNIQUE INDEX "session_token_key" ON "session"("token");

-- CreateIndex
CREATE INDEX "session_userId_idx" ON "session"("userId");

-- CreateIndex
CREATE INDEX "account_userId_idx" ON "account"("userId");

-- CreateIndex
CREATE INDEX "verification_identifier_idx" ON "verification"("identifier");

-- CreateIndex
CREATE UNIQUE INDEX "retailers_prismID_key" ON "retailers"("prismID");

-- CreateIndex
CREATE UNIQUE INDEX "sku_name_retailerId_key" ON "sku_name"("retailerId");

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
